---
language: python
python: "3.8"
sudo: required
services:
  - docker

before_install:
  - docker --version
install:
  - pip install molecule docker
script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
